[2025-04-29T15:18:43.804+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-29T15:18:44.215+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: random_user_pipeline.insert_postgres manual__2025-04-29T15:18:26.722717+00:00 [queued]>
[2025-04-29T15:18:44.236+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: random_user_pipeline.insert_postgres manual__2025-04-29T15:18:26.722717+00:00 [queued]>
[2025-04-29T15:18:44.237+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-29T15:18:44.269+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_postgres> on 2025-04-29 15:18:26.722717+00:00
[2025-04-29T15:18:44.282+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'random_user_pipeline', 'insert_***', 'manual__2025-04-29T15:18:26.722717+00:00', '--job-id', '180', '--raw', '--subdir', 'DAGS_FOLDER/random_user_pipeline.py', '--cfg-path', '/tmp/tmp05vp3vir']
[2025-04-29T15:18:44.286+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=209) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-29T15:18:44.286+0000] {standard_task_runner.py:91} INFO - Job 180: Subtask insert_***
[2025-04-29T15:18:44.287+0000] {standard_task_runner.py:63} INFO - Started process 210 to run task
[2025-04-29T15:18:45.520+0000] {task_command.py:426} INFO - Running <TaskInstance: random_user_pipeline.insert_postgres manual__2025-04-29T15:18:26.722717+00:00 [running]> on host 713af255ad8d
[2025-04-29T15:18:47.846+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='random_user_pipeline' AIRFLOW_CTX_TASK_ID='insert_***' AIRFLOW_CTX_EXECUTION_DATE='2025-04-29T15:18:26.722717+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-29T15:18:26.722717+00:00'
[2025-04-29T15:18:47.848+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-29T15:18:47.867+0000] {logging_mixin.py:188} INFO - >>> Raw input type: <class 'str'>
[2025-04-29T15:18:47.868+0000] {logging_mixin.py:188} INFO - >>> Input is a string, trying to parse as JSON...
[2025-04-29T15:18:47.869+0000] {logging_mixin.py:188} INFO - >>> ERROR: Input string is not valid JSON.
[2025-04-29T15:18:47.870+0000] {logging_mixin.py:188} INFO - >>> JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
[2025-04-29T15:18:47.870+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-29T15:18:47.871+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-29T15:18:48.298+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=random_user_pipeline, task_id=insert_***, run_id=manual__2025-04-29T15:18:26.722717+00:00, execution_date=20250429T151826, start_date=20250429T151844, end_date=20250429T151848
[2025-04-29T15:18:48.364+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-29T15:18:48.860+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-29T15:18:48.864+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
