[2025-04-29T15:22:05.170+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-29T15:22:05.623+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: random_user_pipeline.insert_postgres manual__2025-04-29T15:21:48.777070+00:00 [queued]>
[2025-04-29T15:22:05.639+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: random_user_pipeline.insert_postgres manual__2025-04-29T15:21:48.777070+00:00 [queued]>
[2025-04-29T15:22:05.641+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-29T15:22:05.668+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_postgres> on 2025-04-29 15:21:48.777070+00:00
[2025-04-29T15:22:05.678+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'random_user_pipeline', 'insert_***', 'manual__2025-04-29T15:21:48.777070+00:00', '--job-id', '183', '--raw', '--subdir', 'DAGS_FOLDER/random_user_pipeline.py', '--cfg-path', '/tmp/tmpyfyz0q4z']
[2025-04-29T15:22:05.682+0000] {standard_task_runner.py:91} INFO - Job 183: Subtask insert_***
[2025-04-29T15:22:05.683+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=209) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-29T15:22:05.683+0000] {standard_task_runner.py:63} INFO - Started process 210 to run task
[2025-04-29T15:22:06.937+0000] {task_command.py:426} INFO - Running <TaskInstance: random_user_pipeline.insert_postgres manual__2025-04-29T15:21:48.777070+00:00 [running]> on host c775053851ab
[2025-04-29T15:22:09.376+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='random_user_pipeline' AIRFLOW_CTX_TASK_ID='insert_***' AIRFLOW_CTX_EXECUTION_DATE='2025-04-29T15:21:48.777070+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-29T15:21:48.777070+00:00'
[2025-04-29T15:22:09.378+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-29T15:22:09.408+0000] {logging_mixin.py:188} INFO - >>> Raw input type: <class 'str'>
[2025-04-29T15:22:09.409+0000] {logging_mixin.py:188} INFO - >>> Input is a string, trying to parse...
[2025-04-29T15:22:09.414+0000] {logging_mixin.py:188} INFO - >>> Parsed using ast.literal_eval (Python dict string).
[2025-04-29T15:22:09.415+0000] {logging_mixin.py:188} INFO - >>> Data is now a Python dictionary.
[2025-04-29T15:22:09.416+0000] {logging_mixin.py:188} INFO - >>> Number of products: 10
[2025-04-29T15:22:09.416+0000] {logging_mixin.py:188} INFO - >>> First product preview: {'id': 1, 'name': 'Ad optio dolorum magni quis.', 'description': 'Voluptate odit error velit facilis ut fuga at architecto. Quasi sed ut temporibus consequatur eum labore iure. Fuga nam quos porro ex molestiae. Aut reprehenderit qui libero accusantium.', 'ean': '6516474099890', 'upc': '344954508671', 'image': 'http://placeimg.com/640/480/tech', 'images': [{'title': 'Sed deserunt tempore animi.', 'description': 'Non repellat inventore numquam ipsam minima id consequatur quaerat. Ut quam quo est fuga autem nam qui. Facere praesentium ullam odio optio tempore qui.', 'url': 'https://picsum.photos/640/480'}, {'title': 'Fugit animi est aut.', 'description': 'Eos quasi quis quia blanditiis impedit sunt rerum. Laborum facere facilis voluptate iure non.', 'url': 'https://picsum.photos/640/480'}, {'title': 'At id provident et neque.', 'description': 'Cum distinctio quibusdam eos. Voluptas unde qui autem iste aperiam. Vel omnis fuga non dolor.', 'url': 'https://picsum.photos/640/480'}], 'net_price': 10166037.1, 'taxes': 22, 'price': 12402565.26, 'categories': [99, 100, 101, 102, 103], 'tags': ['cupiditate', 'necessitatibus', 'commodi', 'nihil']}
[2025-04-29T15:22:09.417+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-29T15:22:09.418+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-29T15:22:09.911+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=random_user_pipeline, task_id=insert_***, run_id=manual__2025-04-29T15:21:48.777070+00:00, execution_date=20250429T152148, start_date=20250429T152205, end_date=20250429T152209
[2025-04-29T15:22:09.963+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-29T15:22:10.400+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-29T15:22:10.407+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
